### ISSUE TITLE
isFunction is not a function at defineComponent (runtime-core.esm-bundler.js:2331:10) at vue-router.mjs:2233:38 

### ISSUE THREAD

**Issue by HakobYeroyanEst** [ManukMinasyan/vue3-observe-visibility#1]
Vue version: ^3.3.8

the error occurred if I am trying to import it after `import App from "./App.vue"`

like this:
`import App from "./App.vue"`
`import VueObserveVisibility from "vue3-observe-visibility"`

**Comment by HakobYeroyanEst** [comment]
Update
The error fixed after I switched them

`import VueObserveVisibility from "vue3-observe-visibility"`
`import App from "./App.vue"`

**Comment by ManukMinasyan** [comment]
@HakobYeroyanEst, I'm currently unable to reproduce the error you've mentioned. Could you kindly set up a sandbox or provide an environment where this error occurs so that I can better understand the issue and assist you effectively? Thank you!

**Comment by HakobYeroyanEst** [comment]
update:
The issue was related to the @nerd305/firebase-vuetify-auth package 
particularly this line: `import { useAuthStore } from "@nerd305/firebase-vuetify-auth"`

tried, but couldn't reproduce the issue in the sandbox. All works good

probably the issue is related to the both packages' defineComponent functions conflict
